### ISSUE TITLE
[Node.js flavor] Separate database for tests 

### ISSUE THREAD

**Issue by akucintavalent** [DeSmart/dekick#19]
We are reluctant to write tests in our Node.js project because those tests would use our primary/regular database. At this very moment, DeKick creates only one database for Node.js projects. I would like it to create two databases, one for regular use and one for tests. And whenever we run tests I'd like them to use the database dedicated to tests.

**Comment by dooshek** [comment]
This is fixed in 2.1.0 release but there's no express boilerplate ready, so this won't be fixed until it's created. Leaving open for now.
